## Name : Sadnan Saquif
## Handle: SSaquif

## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("./data/president_heights.csv")

names = df['name'].to_numpy()
heights = df['height(cm)'].to_numpy()
# print(heights)

mean = heights.mean()
std = heights.std()

minIndex = heights.argmin()
maxIndex = heights.argmax()

print(f"Mean Height: {round(mean,2)}")
print(f"Standard Dev: {round(std,2)}")
print(f"Shortest: {names[minIndex]}, {heights[minIndex]}")
print(f"Tallest: {names[maxIndex]}, {heights[maxIndex]}")

Mean Height: 179.74
Standard Dev: 6.93
Shortest: James Madison, 163
Tallest: Abraham Lincoln, 193


# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  


In [2]:
def p(x,coeff_list):
    polynomial = np.array([coeff*(x**i) for i, coeff in enumerate(coeff_list)])
    res = np.cumsum(polynomial)
    return res[-1]
    
print(p(5, [1, 1]))
print(p(5, [2, 1, 1]))

6
32


## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the **sepal length**. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

### Resources
[softmax](https://www.youtube.com/watch?v=8ps_JEW42xs)

In [3]:
def softmax(x):
    numer = np.exp(x)
    denom = np.sum(numer)
    softmax = numer/denom
    return softmax

df = pd.read_csv('./data/iris.csv')
sepal_lengths = df['sepallength'].to_numpy()
print(softmax(sepal_lengths))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

In [4]:
# Test
from scipy.special import softmax as scipy_softmax

print(scipy_softmax(sepal_lengths))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [5]:
def unique_counts(arr):
    # rows == number of items in arr
    # cols == max valued Integer in array
    rows = len(arr)
    cols = np.max(arr)
    
    # Initialized Output Matrix with all bits set to 0
    matrix = np.full((rows,cols),0)
    
    for row_i, row in enumerate(arr):
        numbers, counts = np.unique(row, return_counts=True)
        
        for i, num in enumerate(numbers):
            col = num - 1
            matrix[row_i, col] = counts[i]
            
    return matrix

# Fixed Seed random array
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)
print(unique_counts(arr))

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [6]:
# Assumption: Numbers in array are Integers >= 0

def one_hot_enc(arr):
    # rows == number of items in arr
    # cols == max valued Integer in array
    rows = len(arr)
    cols = np.max(arr)
    
    # Bits Matrix initialized with all bits set to 0
    matrix = np.full((rows,cols), 0)
    
    for i, num in enumerate(arr):
        # If num is 0 dont change the row
        if num != 0:
            col = num - 1
            matrix[i, col] = 1
    return matrix

# Test
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)
print(one_hot_enc(arr))
print('\n')
np.random.seed(55) # Has a 0 in the array
arr = np.random.randint(0,8, size=6)
print(arr)
print(one_hot_enc(arr))

[2 3 2 2 2 1]
[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


[5 2 7 0 5 5]
[[0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]]


## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [7]:
def sorted(q):
    q = np.array(q)
    print(f"q = {q}")
    q_sum = np.cumsum(q)
    print(f"q sum = {q_sum}")
    U = np.random.uniform(0,1)
    print(f"U = {U}")
    return np.searchsorted(q_sum, U)

sorted([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

q = [0.1 0.2 0.3 0.4 0.5 0.6]
q sum = [0.1 0.3 0.6 1.  1.5 2.1]
U = 0.2425227014980641


1

In [8]:
class DiscreteRV():
    def __init__(self, q=None):
        try:
            self.q = np.asarray(q)
            self.q_sum = np.cumsum(self.q)
        # NTS: Need to learn more about common exceptions
        except:
            raise Exception('Invalid')
    
    def draw(self, k=1):
        # numpy  array of size k
        draws = []
        print(f"q sum = {self.q_sum}")
        for i in range(k): 
            U = np.random.uniform(0,1)
            print(f"U{i+1} = {U}")
            draws.append(np.searchsorted(self.q_sum, U))
            
        return draws
        
DiscreteRV([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]).draw(k=3)

# Exception
# DiscreteRV([{},[]])

q sum = [0.1 0.3 0.6 1.  1.5 2.1]
U1 = 0.5311238298072531
U2 = 0.2855442354647988
U3 = 0.8626303770516396


[2, 1, 3]

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [9]:
# Assumption: The left of first num is last num, and right of last num is first num

def peaks_version_0(arr):
    peak_indices = []
    for i , num in enumerate(arr):
        # Circular Array
        if num > arr[i-1] and num > arr[(i+1)%len(arr)]:
            peak_indices.append(i)
            
    return peak_indices
            
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
peaks_version_0(a)

[2, 5]

In [10]:
def peaks(arr):
    print(arr)
    
    left_shift = np.roll(arr, -1)
    print(left_shift)

    right_shift = np.roll(arr, 1)
    print(right_shift)

    right_peak_indices = np.where(arr > left_shift)
    print(right_peak_indices)

    left_peak_indices = np.where(arr > right_shift) 
    print(left_peak_indices)

    peak_indices = np.intersect1d(right_peak_indices, left_peak_indices)
    print(peak_indices)
    
    return peak_indices

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
peaks(a)

[1 3 7 1 2 6 0 1]
[3 7 1 2 6 0 1 1]
[1 1 3 7 1 2 6 0]
(array([2, 5]),)
(array([1, 2, 4, 5, 7]),)
[2 5]


array([2, 5])

# In Class Exercises, Big O

In [11]:
def fib(n):
    if n < 2:
        return n
    return fib(n-1) + fib(n-2)

fib(9)

def fib(n):
    fibArr = [0,1]
    
    for i in range(2,n+1):
        x = fibArr[i-1]
        y = fibArr[i-2]
        fibArr.append(x+y)
        print(fibArr)
    
    return fibArr[n]
fib(9)

[0, 1, 1]
[0, 1, 1, 2]
[0, 1, 1, 2, 3]
[0, 1, 1, 2, 3, 5]
[0, 1, 1, 2, 3, 5, 8]
[0, 1, 1, 2, 3, 5, 8, 13]
[0, 1, 1, 2, 3, 5, 8, 13, 21]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


34

In [12]:
def merge_sort(a):
    size = len(a)
    if size > 1:
        middle = size//2
        
#         print(f"l {a[0:middle]}")
#         print(f"r {a[middle:]}")
        
        left = merge_sort(a[0:middle])
        right = merge_sort(a[middle:])
        
        return merge(left,right)
    
    else:
        return a
    
def merge(left,right):
    left = left.copy()
    right = right.copy()
    resArr = []
    leftIndex = 0
    rightIndex = 0
    print(left, right)
    
    while(leftIndex < len(left) and rightIndex < len(right)):
        print(left[leftIndex] , right[rightIndex])
        if(left[leftIndex] < right[rightIndex]):
            resArr.append(left[leftIndex])
            leftIndex += 1
        else:
            resArr.append(right[rightIndex])
            rightIndex += 1
        print(resArr)
     
    resArr = resArr + right[rightIndex:] + left[leftIndex:]
    print(resArr)
    
#     print(f"right {right}")
#     print(f"left {left}")
#     print(f"resA {resArr}")
    
    return resArr

merge_sort([10, -1, 2, 5, 0, 6, 4, -5])

[10] [-1]
10 -1
[-1]
[-1, 10]
[2] [5]
2 5
[2]
[2, 5]
[-1, 10] [2, 5]
-1 2
[-1]
10 2
[-1, 2]
10 5
[-1, 2, 5]
[-1, 2, 5, 10]
[0] [6]
0 6
[0]
[0, 6]
[4] [-5]
4 -5
[-5]
[-5, 4]
[0, 6] [-5, 4]
0 -5
[-5]
0 4
[-5, 0]
6 4
[-5, 0, 4]
[-5, 0, 4, 6]
[-1, 2, 5, 10] [-5, 0, 4, 6]
-1 -5
[-5]
-1 0
[-5, -1]
2 0
[-5, -1, 0]
2 4
[-5, -1, 0, 2]
5 4
[-5, -1, 0, 2, 4]
5 6
[-5, -1, 0, 2, 4, 5]
10 6
[-5, -1, 0, 2, 4, 5, 6]
[-5, -1, 0, 2, 4, 5, 6, 10]


[-5, -1, 0, 2, 4, 5, 6, 10]